"""add width and height to note

Revision ID: 4701d075b7ac
Revises: 5773021c8179
Create Date: 2026-06-30 23:50:03.276472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4701d075b7ac'
down_revision: Union[str, Sequence[str], None] = '5773021c8179'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('width', sa.Float(), nullable=True, server_default='200.0'))
    op.add_column('note', sa.Column('height', sa.Float(), nullable=True, server_default='120.0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('note', 'height')
    op.drop_column('note', 'width')
    # ### end Alembic commands ###
