"""test

Revision ID: 5773021c8179
Revises: 
Create Date: 2026-06-30 23:41:06.231973

"""
from typing import Sequence, Union

from alembic import op # type: ignore
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '5773021c8179'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('book', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('book_abbrev', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chapter_start', sa.Integer(), nullable=False),
    sa.Column('verse_start', sa.Integer(), nullable=True),
    sa.Column('chapter_end', sa.Integer(), nullable=True),
    sa.Column('verse_end', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('verse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('book_abbrev', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chapter', sa.Integer(), nullable=False),
    sa.Column('verse_number', sa.Integer(), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('translation', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('layer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portal_id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('colour', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['portal_id'], ['portal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('highlight',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('layer_id', sa.Integer(), nullable=False),
    sa.Column('verse_id', sa.Integer(), nullable=False),
    sa.Column('start_offset', sa.Integer(), nullable=True),
    sa.Column('end_offset', sa.Integer(), nullable=True),
    sa.Column('full_verse', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['layer_id'], ['layer.id'], ),
    sa.ForeignKeyConstraint(['verse_id'], ['verse.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('highlight_id', sa.Integer(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['highlight_id'], ['highlight.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('note')
    op.drop_table('highlight')
    op.drop_table('layer')
    op.drop_table('verse')
    op.drop_table('portal')
    # ### end Alembic commands ###
