"""increase values of box

Revision ID: aada66a1606d
Revises: 4701d075b7ac
Create Date: 2026-06-30 23:59:23.979285

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "aada66a1606d"
down_revision: Union[str, Sequence[str], None] = "4701d075b7ac"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
